# Generated by Django 5.2.17 on 2026-09-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "references",
            "0002_reference_description_cs_reference_description_en_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["name_cs"], name="references__name_f29fb0_idx-cs"
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["name_en"], name="references__name_f29fb0_idx-en"
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["description_cs"], name="references__descrip_d68adb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["description_en"], name="references__descrip_d46028_idx"
            ),
        ),
    ]
