# Generated by Django 5.1.7 on 2025-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('issue_url', models.URLField(max_length=255)),
                ('comment_url', models.URLField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['created_on'], name='activities__created_5cbe32_idx'), models.Index(fields=['title'], name='activities__title_668fec_idx')],
            },
        ),
    ]
