# Generated by Django 5.1.7 on 2025-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('issue_url', models.URLField(max_length=255)),
                ('comment_url', models.URLField(max_length=255)),
            ],
        ),
    ]
